app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
  # root
  path('', views.home, name='home'),
  #other 
  path('signin', views.sign_in, name='signin'),
  path('signout', views.sign_out, name='signout'),
  path('callback', views.callback, name='callback'),
  path('notebook', views.notebook, name='notebook'),
  path('createnb', views.createnb,name="createnb"),
  path('getnb', views.getnb,name="getnb"),
]

notebook/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from auth_helper import get_sign_in_flow, get_token_from_code, store_user, remove_user_and_token, get_token
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from datetime import datetime, timedelta
from dateutil import tz, parser
from graph_helper import *

def getnb(request):
  response = None
  context = initialize_context(request)
  context["operation_type"] = "getnb"
  token = get_token(request)
  response = get_notebook(token)
  context["notes_list"] = response['value']
  return render(request, 'front_end/result.html', context,status=204)

def createnb(request):
  response = None
  context = initialize_context(request)
  notebook_name = request.POST['notebook_name']
  print(f"notebook name is {notebook_name}")
  token = get_token(request)
  res = create_notebook(token,notebook_name)
  context["operation_type"] = "create"
  return render(request, 'front_end/result.html', context)

def notebook(request):
  context = initialize_context(request)
  return render(request, 'front_end/notebook.html', context)

def sign_out(request):
  # Clear out the user and token
  remove_user_and_token(request)

  return HttpResponseRedirect(reverse('app:home'))

def sign_in(request):
  # Get the sign-in flow
  flow = get_sign_in_flow()
  # Save the expected flow so we can use it in the callback
  try:
    request.session['auth_flow'] = flow
  except Exception as e:
    print(e)
  # Redirect to the Azure sign-in page
  return HttpResponseRedirect(flow['auth_uri'])

def callback(request):
  # Make the token request
  result = get_token_from_code(request)

  #Get the user's profile
  user = get_user(result['access_token'])

  # Store user
  store_user(request, user)
  return HttpResponseRedirect(reverse('app:home'))

def home(request):
  context = initialize_context(request)
  return render(request, 'front_end/home.html', context)

def initialize_context(request):
  context = {}

  # Check for any errors in the session
  error = request.session.pop('flash_error', None)

  if error != None:
    context['errors'] = []
    context['errors'].append(error)

  # Check for user in the session
  context['user'] = request.session.get('user', {'is_authenticated': False})
  return context

app/templates/front_end/home.html
{% extends "front_end/layout.html" %}
{% block content %}
<div class="jumbotron">
  <h1>O365 Notebook using Graph API</h1>
  {% if user.is_authenticated %}
    <h4>Welcome {{ user.name }}!</h4>
    <a href="{% url 'app:notebook' %}" class="btn btn-primary btn-large">NOTEBOOK</a>
  {% else %}
    <a href="{% url 'app:signin' %}" class="btn btn-primary btn-large">Click here to sign in</a>
  {% endif %}
</div>
{% endblock %}

app/templates/front_end/layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>O365 Notebook</title>

    <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
    <link rel="stylesheet"
      href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container">
        <a href="{% url 'app:home' %}" class="navbar-brand">O365 Notebook using Graph-API</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
          aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a href="{% url 'app:home' %}" class="nav-link{% if request.resolver_match.view_name == 'home' %} active{% endif %}">Home</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item" data-turbolinks="false">
                <a class="nav-link{% if request.resolver_match.view_name == 'notebook' %} active{% endif %}" href="{% url 'app:notebook' %}">Notebook</a>
              </li>
            {% endif %}
          </ul>
          <ul class="navbar-nav justify-content-end">
            <li class="nav-item">
              <a class="nav-link external-link" href="https://developer.microsoft.com/graph/docs/concepts/overview" target="_blank">
                <i class="ms-Icon ms-Icon--NavigateExternalInline mr-1" aria-hidden="true"></i>Docs
              </a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link avatar-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                  {% if user.avatar %}
                    <img src="{{ user.avatar }}" class="rounded-circle align-self-center mr-2" style="width: 32px;">
                  {% else %}
                    <img src="{% static 'no-profile-photo.png' %}" class="rounded-circle align-self-center mr-2" style="width: 32px;">
                  {% endif %}
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <h5 class="dropdown-item-text mb-0">{{ user.name }}</h5>
                  <p class="dropdown-item-text text-muted mb-0">{{ user.email }}</p>
                  <div class="dropdown-divider"></div>
                  <a href="{% url 'app:signout' %}" class="dropdown-item">Sign Out</a>
                </div>
              </li>
            {% else %}
              <li class="nav-item">
                <a href="{% url 'app:signin' %}" class="nav-link">Sign In</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <main role="main" class="container">
      {% if errors %}
        {% for error in errors %}
          <div class="alert alert-danger" role="alert">
            <p class="mb-3">{{ error.message }}</p>
            {% if error.debug %}
              <pre class="alert-pre border bg-light p-2"><code>{{ error.debug }}</code></pre>
            {% endif %}
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}{% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"></script>
  </body>
</html>

app/templates/front_end/notebook.html
{% extends "front_end/layout.html" %}
{% block content %}
<div class="jumbotron">
  <p class="lead">O365 Notebook Creation/deletion using Graph-API</p>
  {% if user.is_authenticated %}
    <h4>Welcome {{ user.name }}!</h4>
    <h4> create a note book</h4>
  <form action="{% url 'app:createnb' %}" method="post">{% csrf_token %}
    <input type="text" placeholder='Notebook name' name="notebook_name"></input>
    <input type="submit" class="btn btn-primary btn-large" value="Create a Notebook"/>
  </form>
</br>
<h4> Get a Notebook list </h4>
    <a href="{% url 'app:getnb' %}" class="btn btn-primary btn-large"> Get a Notebook </a>
  {% else %}
    <a href="{% url 'app:signin' %}" class="btn btn-primary btn-large">Click here to sign in</a>
  {% endif %}
</div>
{% endblock %}

app/templates/front_end/result.html
{% extends "front_end/layout.html" %}
{% block content %}
<div class="jumbotron">
  <p class="lead">O365 Notebook Creation/deletion using Graph-API</p>
  {% if user.is_authenticated %}
    {% if operation_type == "create" %}
    <h4> Notebook is Created</h4>
    {% else %}
    <h4> Notebooks are:-</h4>
    {% for note in notes_list %}
    <ul>
      <li>{{ note.displayName }}</li>
    </ul>
    {% endfor %}
    {% endif %}
  <a href="{% url 'app:notebook' %}" class="btn btn-primary btn-large"> GO BACK </a>
  {% else %}
    <a href="{% url 'app:signin' %}" class="btn btn-primary btn-large">Click here to sign in</a>
  {% endif %}
</div>
{% endblock %}